-- Create custom role for Cortex Code access
CREATE ROLE IF NOT EXISTS CORTEX_CODE_USER;

-- Grant required database roles for Cortex Code
GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE CORTEX_CODE_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CORTEX_CODE_USER;

-- Optional: For additional agentic capabilities, grant CORTEX_AGENT_USER instead of or in addition to CORTEX_USER
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE CORTEX_CODE_USER;

-- Grant role to users who need Cortex Code access
-- GRANT ROLE CORTEX_CODE_USER TO USER <username>;

-- To disable Cortex Code for a user, revoke the role:
-- REVOKE ROLE CORTEX_CODE_USER FROM USER <username>;



----Revoking Cortex Code

-- Find all roles that have COPILOT_USER granted
SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.COPILOT_USER;

-- Revoke COPILOT_USER from specific roles (replace <ROLE_NAME> with actual roles from above query)
-- REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE <ROLE_NAME>;

-- Common example: Revoke from PUBLIC to disable for all users by default
REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE PUBLIC;
REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE ROLE_ACC_ADMIN;

-- To re-enable Cortex Code later:
-- GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE <ROLE_NAME>;

GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE PUBLIC;
GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE ROLE_ACC_ADMIN;

GRANT ROLE CORTEX_CODE_USER TO USER RAJIVGUPTA780184;


SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.COPILOT_USER;


-- Disable Cortex Code for Non-Admin Roles
-- Generated based on current grants audit

USE ROLE ACCOUNTADMIN;

-- Revoke COPILOT_USER from custom roles and PUBLIC
-- (Preserving access for: ACCOUNTADMIN, SNOWFLAKE application)

REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE CORTEX_CODE_USER;
REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE PUBLIC;
REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE ROLE_ACC_ADMIN;

-- Verify changes
SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.COPILOT_USER;


SHOW GRANTS TO ROLE PUBLIC;

revoke role CORTEX_CODE_USER from role public;
drop role CORTEX_CODE_USER;


Drop database COCO_ANALYTICS;
Drop database PG_NETWORK_DATABASE;


-- Remove the limit entirely
ALTER ACCOUNT UNSET CORTEX_CODE_CLI_DAILY_EST_CREDIT_LIMIT_PER_USER;
-- Or increase it
ALTER USER rajivgupta780184 SET CORTEX_CODE_CLI_DAILY_EST_CREDIT_LIMIT_PER_USER = 50;


Show parameters like 'CORTEX_CODE_CLI_DAILY_EST_CREDIT_LIMIT_PER_USER'  for user rajivgupta780184;


ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

1356