--Demo 4: Audit Trail - Every chat query is logged


-- Full audit log of all CoCo activity in the last hour
SELECT
  TO_CHAR(START_TIME,'YYYY-MM-DD HH24:MI:SS') AS TIME,
  ROLE_NAME,
  EXECUTION_STATUS,
  LEFT(QUERY_TEXT, 120)  AS QUERY_PREVIEW,
  ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE ROLE_NAME IN ('COCO_RESTRICTED','COCO_FULL_ACCESS')
  AND START_TIME >= DATEADD('hour', -1, CURRENT_TIMESTAMP)
ORDER BY START_TIME DESC;