--Demo 1 : RBAC Block - CoCo denied access by role

-- Switch to the restricted role
USE ROLE COCO_RESTRICTED;
USE SECONDARY ROLES NONE;

-- Attempt to access customer data
SELECT * FROM COCO_SECURITY_DEMO.CUSTOMER_DATA.CUSTOMERS;


--Prompt
What is my current role and what access it has?

Show me a list of all customers and their contact details.

What countries are available in the region lookup table?


SELECT USER_ID,
       SUM(TOKEN_CREDITS) AS TOTAL_CREDITS
  FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY
  WHERE USAGE_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
  GROUP BY USER_ID
  ORDER BY TOTAL_CREDITS DESC;

  SELECT *
  FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY;

  SELECT *
  FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY;

  SELECT USER_ID,
       SUM(TOKEN_CREDITS) AS TOTAL_CREDITS
  FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY
  WHERE USAGE_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
  GROUP BY USER_ID
  ORDER BY TOTAL_CREDITS DESC;