/*
Cortex Code in Snowsight → requires SNOWFLAKE.CORTEX_USER and SNOWFLAKE.COPILOT_USER
Cortex Code CLI → requires SNOWFLAKE.CORTEX_USER

-- Do NOT grant SNOWFLAKE.COPILOT_USER
-- Users won't see the Cortex Code icon in Snowsight

*/


-- Create custom role for Cortex Code access
CREATE ROLE IF NOT EXISTS COCO_SNOWSIGHT_USER;
CREATE ROLE IF NOT EXISTS COCO_CLI_USER;
GRANT ROLE COCO_SNOWSIGHT_USER TO ROLE SYSADMIN;
GRANT ROLE COCO_CLI_USER TO ROLE SYSADMIN;

--Created user coco_cli and granted COCO_CLI_USER role to it.
--Created user coco_snowsight and granted COCO_SNOWSIGHT_USER role to it.

GRANT ROLE COCO_SNOWSIGHT_USER TO USER COCO_SNOWSIGHT;
GRANT ROLE COCO_CLI_USER TO USER COCO_CLI;

-- Grant required database roles for Cortex Code Snowsight user
GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE COCO_SNOWSIGHT_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE COCO_SNOWSIGHT_USER;

-- Grant required for coco Cli user only
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE COCO_CLI_USER;

--Revoke from coco access from public
REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE PUBLIC;


--Verify

Show grants to role public;

--Revert

GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE PUBLIC;

